### ISSUE TITLE
Re-generating SSH host keys

### ISSUE THREAD

**Issue by zimbatm** [nix-community/srvos#148]
**Describe the bug**

I noticed that hosts tend to get new SSH keys on reboot. It might be a bug in cloud-init.

**To Reproduce**

I don't have a good repro right now. It happened to me multiple times, both on Hetzner Cloud and Vultr that the sops-nix age keys are different and the host cannot decrypt the secrets anymore. TBI.

**Expected behavior**

Keep the same SSH key-pair once it's generated.

**System information**

**Additional context**

**Comment by Mic92** [comment]
Not seen this yet.

**Comment by surfaceflinger** [comment]
I workaround it this way
```
services.cloud-init.settings = {
    ssh_deletekeys = false;
};
```

I guess cloud-init does that to make sure SSH keys from AMIs etc. are gone and every instance has their own keys. It should do it once, at the first boot. If you have ephemeral setup, something in `/var/lib` or `/etc` might get lost and cloud-init will think it's the first boot again.

**Comment by zimbatm** [comment]
good catch. there is another deeper bug where cloud-init thinks it's a new host, but that's a good workaround.
