### ISSUE TITLE
Add DigitalOcean support

### ISSUE THREAD

**Issue by bbigras** [nix-community/srvos#309]
For some reason I can't activate a nix-config using srvos on digitalocean.

I'm not done testing, but it seems I had to set this:

```nix
  networking.useNetworkd = false;
  networking.useDHCP = true;
  networking.nameservers = [ "1.1.1.1" "1.0.0.1" ];
```

Also, I don't know if digitalocean has cloud-init and if it matters.

old issue #287

**Comment by bbigras** [comment]
It seems that digital ocean doesn't use dhcp. While I was playing with nixos-anywhere recently, this seemed to work:

- use cloud-init with `srvos.nixosModules.mixins-cloud-init`
- use `(modulesPath + "/virtualisation/digital-ocean-config.nix")`
- `networking.useDHCP = lib.mkForce false;`

**Comment by Mic92** [comment]
A digitalocean module has been added in the meantime.
