### ISSUE TITLE
hardware/amazon: redundant `services.cloud-init.enable = true`?

### ISSUE THREAD

**Issue by bbigras** [nix-community/srvos#414]
https://github.com/nix-community/srvos/blob/e4252aa777482dc9d4cacd779ae29115de69b7ba/nixos/hardware/amazon/default.nix#L13-L14

Isn't `cloud-init` already set in `cloud-init.nix`?
https://github.com/nix-community/srvos/blob/e4252aa777482dc9d4cacd779ae29115de69b7ba/nixos/mixins/cloud-init.nix#L3-L4

**Comment by hbjydev** [comment]
`cloud-init` isn't exclusive to AWS, hence it having its own mixin separate from the Amazon module. It's available on _most_ cloud providers out there.

**Comment by bbigras** [comment]
but `amazon/default.nix` also imports `../../mixins/cloud-init.nix`.

**Comment by Mic92** [comment]
Yes. Looks like this can be dropped.
