### ISSUE TITLE
[darwin] Common host module sets removed option services.openssh.authorizedKeyFiles

### ISSUE THREAD

**Issue by aftix** [nix-community/srvos#456]
[This file](https://github.com/nix-community/srvos/blob/main/darwin/common/openssh.nix) defines the option `services.openssh.authorizedKeyFiles`, which now causes the failed assertion:
```
The option definition `services.openssh.authorizedKeysFiles' in `/nix/store/7q9yw6ka5wkdb5slmk69g6v0cyzivrvz-source/darwin/common/openssh.nix' no longer has any effect; please remove it.
```

since [this commit](https://github.com/LnL7/nix-darwin/blob/b833d4a32d965e6393a63b2c91b46eca2a5030d8/modules/programs/ssh/default.nix#L100).

**Comment by Yash-Garg** [comment]
Having the same issue.
